### ISSUE TITLE
Projects still need better pre-trained models

### ISSUE THREAD

**Issue by Baiyuetribe** [Averyyy/PyTorch-Anime2Real#1]

**Comment by Baiyuetribe** [comment]
I have given the project a minimal demo of ncnn, from the results are not very stunning
![photo_2022-06-02_23-28-51](https://user-images.githubusercontent.com/43716063/171667434-24338e3c-a184-41c3-b70a-0f3ba80a7943.jpg)
https://github.com/Baiyuetribe/ncnn-models/tree/main/style_transfer/anime2real

**Comment by Averyyy** [comment]
Hi Baiyue，
thx for your attention to the project! We just started the project a week ago and we are still working on it. Definitely, it needs much improvement.
